CREATE PROCEDURE INSERTJID
@SNO        		int,
@JID        		varchar(200),
@JOURNALTITLE	 	varchar(150),
@PRODUCTIONSITE       	varchar(100),
@CUSTOMER       	varchar(100),
@ROWID	       		int OUTPUT
AS
INSERT INTO ELSSTYLESHEET
  (SNO,JID, JOURNALTITLE, PRODUCTIONSITE,CUSTOMER) 
  VALUES (@SNO,@JID, @JOURNALTITLE, @PRODUCTIONSITE, @CUSTOMER);

SET @rowID = @@IDENTITY
GO

CREATE PROCEDURE CountJID
AS
SELECT COUNT(JID) FROM ELSSTYLESHEET
GO


CREATE PROCEDURE DeleteJID
@JID	      varchar
AS
DELETE FROM ELSSTYLESHEET WHERE JID = @JID
GO


CREATE PROCEDURE GetAllEmployees
AS
SELECT * FROM ELSSTYLESHEET
GO


CREATE PROCEDURE GetJID
@JID	  VARCHAR
AS
SELECT * FROM Employees
  WHERE JID = @JID
GO
