#pragma checksum "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "34D06128F5702B61A6E8EB3C4464088ED1490467"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class GenerateOrder : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 3 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
    protected global::System.Web.UI.WebControls.Label lblUser;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 2 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 401 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 2 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 2 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 397 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 2 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 2 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 406 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class generateorder_aspx : global::GenerateOrder, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.generateorder_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public generateorder_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/GenerateOrder.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.generateorder_aspx.@__initialized == false)) {
                dependencies = new string[6];
                dependencies[0] = "~/GenerateOrder.aspx";
                dependencies[1] = "~/FullMaster.master";
                dependencies[2] = "~/FullMaster.master.cs";
                dependencies[3] = "~/MasterPage.master";
                dependencies[4] = "~/MasterPage.master.cs";
                dependencies[5] = "~/GenerateOrder.aspx.cs";
                global::ASP.generateorder_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.generateorder_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Welcome to XML Order Creation and Integration Application");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        235,
                        57,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=14.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.generateorder_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.generateorder_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTitle(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 2 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 2 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblUser() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblUser = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__ctrl.ID = "lblUser";
            
            #line default
            #line hidden
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__ctrl.Text = "User Not Found";
            
            #line default
            #line hidden
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__ctrl.Font.Size = global::System.Web.UI.WebControls.FontUnit.Small;
            
            #line default
            #line hidden
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        383,
                        108,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlUserWelcome(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__ctrl1 = this.@__BuildControllblUser();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"

<A><IMG 
      alt=""View Source"" 
      src=""ImagesAndStyleSheet/Login.jpg"" 
      border=0></A>
     
          <H4>Goals and Objectives</H4>
      <P>This application can generate xml order at login stage and simultaneously login the article in TIS Database. So you just need to generate the xml order and your article will be login into TIS Database also.
        Entries can be done in all stages (Fresh, Revise, Printer, FAX, SGML etc.).
</P>

      <P></P>
      <H4>Recent Updates:</H4>
      <ul>
      <li>Now user can update any existing order and application will do the version control automatically for xml orders.</li>
      <li>User can also check for orders by clicking on <b><u>Order Logs</u></b> menu.</li>
      <li>To read the details about your xml order, Please click on <b><u>XML Browser</u></b> menu.</li>
      </ul>
      
      <P></P>
      <P></P>
      <H4>Features:</H4>
      <ul>
      <li>Application reads the input from input location and provides necessary details.</li>
      <li>Xml Order is Generated automatically.</li>
      <li>Xml Order is Validated for correctness.</li>
      <li>Article is automatically integrated into TIS.</li>
      <li>Xml Order will be used by FMS.</li>
      </ul>
      

");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        586,
                        1277,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlOrderContent(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(generateorder_aspx @__ctrl) {
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__ctrl.MasterPageFile = "FullMaster.master";
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__ctrl.Title = "Untitled Page";
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 2 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            this.AddContentTemplate("TitleThis", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlTitle)));
            
            #line default
            #line hidden
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            this.AddContentTemplate("UserThis", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlUserWelcome)));
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            this.AddContentTemplate("ContentBody", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlOrderContent)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\WinCVS\ThimeXMLORDER\GenerateOrder.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.generateorder_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 789042286;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
