#pragma checksum "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "72B80F212F062D8BC04E12E0BB0C25A58330EBD0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class OrderViewer : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label lblUser;
    
    #line default
    #line hidden
    
    
    #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label Label4;
    
    #line default
    #line hidden
    
    
    #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.DropDownList cmbAccount;
    
    #line default
    #line hidden
    
    
    #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label Label1;
    
    #line default
    #line hidden
    
    
    #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.DropDownList cmbJID;
    
    #line default
    #line hidden
    
    
    #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label Label3;
    
    #line default
    #line hidden
    
    
    #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.DropDownList cmbStage;
    
    #line default
    #line hidden
    
    
    #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label Label2;
    
    #line default
    #line hidden
    
    
    #line 97 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtAID;
    
    #line default
    #line hidden
    
    
    #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.ImageButton ImageButton5;
    
    #line default
    #line hidden
    
    
    #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.ImageButton ImageButton1;
    
    #line default
    #line hidden
    
    
    #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label txtOrderNotFound;
    
    #line default
    #line hidden
    
    
    #line 134 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Xml Xml1;
    
    #line default
    #line hidden
    
    
    #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 401 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 397 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 406 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class orderviewer_aspx : global::OrderViewer, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.orderviewer_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public orderviewer_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/OrderViewer.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.orderviewer_aspx.@__initialized == false)) {
                dependencies = new string[4];
                dependencies[0] = "~/OrderViewer.aspx";
                dependencies[1] = "~/OrderViewer.aspx.cs";
                dependencies[2] = "~/MasterPage.master";
                dependencies[3] = "~/MasterPage.master.cs";
                global::ASP.orderviewer_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.orderviewer_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Welcome to XML Order Creation and Integration Application");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        234,
                        57,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=14.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.orderviewer_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.orderviewer_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTitle(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("<span id=\"aa\"></span> ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        384,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblUser() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblUser = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "lblUser";
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "";
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Size = global::System.Web.UI.WebControls.FontUnit.Small;
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        406,
                        94,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlUserWelcome(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl2 = this.@__BuildControllblUser();
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        590,
                        12,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
    <div>
        <table border=""0""  cellpadding=""0"" cellspacing=""0"" style=""width: 100%; height: 5%; border-top-style: none; border-right-style: none; border-left-style: none; border-bottom-style: none;"" id=""TABLE1"" onclick=""return TABLE1_onclick()"">
<!--            <tr style=""height:110px; width: 100%; background-color: #f2f2f2;"">
 <td colspan=""2"" style=""background-image:url(header.gif);background-repeat:no-repeat; background-position:center"" width=100% >
                </td>
            </tr>-->
            <tr style=""width: 22%;height: 100%"" >
                <td style=""height: 99px; width: 238px"">                   

                </td>
                <td style=""width: 74%;height: 99px "" valign=""top"" align=left>
                        <table style=""width: 100%; height: 40px"" >
                            <tr>
<td style=""width:28%; height: 39%;"" valign=""top"">
                                    <table>
                                        <tr>
                                            <td style=""width: 100px"" valign=top>");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        635,
                        1067,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel4() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "Label4";
            
            #line default
            #line hidden
            
            #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "Account";
            
            #line default
            #line hidden
            
            #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Gray;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1702,
                        97,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                    " +
                    "        <td style=\"width: 39px\">                                                " +
                    "");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1799,
                        161,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control8() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 30 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 30 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "JWUSA";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control9() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 31 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 31 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "JWUK";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control10() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 32 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 32 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "JWVCH";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control7(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl2 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl3 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlcmbAccount() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.cmbAccount = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "cmbAccount";
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative");
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(150D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.@__BuildControl__control7(@__ctrl.Items);
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.cmbAccount_SelectedIndexChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1960,
                        499,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                                </td>
                                        </tr>
                                        <tr>
                                            <td style=""width: 100px; height: 19px;"">
                                    </td>
                                            <td style=""width: 100%; height: 19px;"" >
                                    </td>
                                        </tr>
                                    </table>
                                    </td>
                                <td style=""width:28%; height: 39%;"" valign=""top"">
                                    <table>
                                        <tr>
                                            <td style=""width: 139px; height: 25px;"" valign=top>");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2459,
                        813,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "Label1";
            
            #line default
            #line hidden
            
            #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "JID";
            
            #line default
            #line hidden
            
            #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Gray;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3272,
                        93,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                    " +
                    "        <td style=\"width: 39px; height: 25px;\">\r\n                               " +
                    "                 ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3365,
                        178,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlcmbJID() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.cmbJID = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "cmbJID";
            
            #line default
            #line hidden
            
            #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative");
            
            #line default
            #line hidden
            
            #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(102D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.cmbJID_SelectedIndexChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3543,
                        208,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"

                                            </td>
                                        </tr>
                                        <tr>
                                            <td style=""width: 139px; height: 19px;"">
                                    </td>
                                            <td style=""width: 100%; height: 19px;"" >
                                    </td>
                                        </tr>
                                    </table>
                                    </td>
                                <td style=""width: 32%; height: 39%;"" valign=""top"" >
                                    <table style=""height: 20px"">
                                        <tr>
                                        <td style=""width: 100px; height: 15px;"" valign=top>
                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3751,
                        868,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel3() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "Label3";
            
            #line default
            #line hidden
            
            #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "STAGE";
            
            #line default
            #line hidden
            
            #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Gray;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4619,
                        95,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                    " +
                    "        <td style=\"width: 42px; height: 15px;\">\r\n                               " +
                    "             ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4714,
                        174,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control16() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 71 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 71 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "Fresh";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control17() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 72 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 72 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "MCE";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control18() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 73 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 73 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "Revise";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control19() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 74 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 74 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "FAX";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control20() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 75 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 75 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "SGML";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control21() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 76 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 76 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "Web";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control22() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 77 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 77 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "Printer";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control15(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl2 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl3 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl4 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl5;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl5 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl6;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl6 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl7;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl7 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlcmbStage() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.cmbStage = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "cmbStage";
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative");
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(155D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.@__BuildControl__control15(@__ctrl.Items);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4888,
                        741,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control23() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"

                                                &nbsp;</td>
                                        </tr>
                                        <tr>
                                            <td style=""width: 46px; height: 14px;"">
                                    </td>
                                            <td style=""width: 100%; height: 14px;"">
</td>
                                        </tr>
                                    </table>
                                </td>
                                <td style=""height: 39%;"" valign=""top"">
                                    <table>
                                        <tr>
                                            <td style=""width: 46px"" valign=top>
                                            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5629,
                        798,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel2() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "Label2";
            
            #line default
            #line hidden
            
            #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "AID/ISSUE";
            
            #line default
            #line hidden
            
            #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Gray;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6427,
                        99,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control24() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                    " +
                    "        <td style=\"width: 28px\">\r\n                                              " +
                    "  ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6526,
                        163,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtAID() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 97 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtAID = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 97 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "txtAID";
            
            #line default
            #line hidden
            
            #line 97 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6689,
                        81,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control25() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                            </td>

                                        </tr>
                                        <tr>
                                            <td colspan=2 style=""width: 100px; height: 19px;"">
                                            </td>
                                        </tr>
                                    </table>
                                    </td>                                
                                <td style=""width: 100%; height: 39%;"" valign=""top"">
                                    <table>
                                        <tr>
                                            <td style=""width: 100px; height: 20px;"">
                                    </td>
                                            <td style=""width: 100px; height: 20px;"">");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6770,
                        852,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControlImageButton5() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            this.ImageButton5 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "ImageButton5";
            
            #line default
            #line hidden
            
            #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative; z-index: 100;");
            
            #line default
            #line hidden
            
            #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ImageUrl = "button_view.gif";
            
            #line default
            #line hidden
            
            #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Click += new System.Web.UI.ImageClickEventHandler(this.ImageButton5_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7622,
                        150,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"&nbsp;<br />
                                                
                                    </td>
                                        </tr>
                                        <tr>
                                            <td style=""width: 100px; height: 19px;"">
                                            </td>
                                            <td style=""width: 100px; height: 19px;"">
                                                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7772,
                        471,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControlImageButton1() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            this.ImageButton1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "ImageButton1";
            
            #line default
            #line hidden
            
            #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative");
            
            #line default
            #line hidden
            
            #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ImageUrl = "btnhome.gif";
            
            #line default
            #line hidden
            
            #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Click += new System.Web.UI.ImageClickEventHandler(this.ImageButton1_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8243,
                        130,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control27() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                            </td>
                                        </tr>
                                    </table>
                                </td>                                
                                <td valign=top>
</td>
                           </tr>
                            <tr>                                
                            </tr>
                        </table>
                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8373,
                        462,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControltxtOrderNotFound() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.txtOrderNotFound = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "txtOrderNotFound";
            
            #line default
            #line hidden
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position:relative");
            
            #line default
            #line hidden
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(723D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.OrangeRed;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8835,
                        139,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control28() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("</td>\r\n            </tr>\r\n        </table>\r\n\t");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8974,
                        45,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Xml @__BuildControlXml1() {
            global::System.Web.UI.WebControls.Xml @__ctrl;
            
            #line 134 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Xml();
            
            #line default
            #line hidden
            this.Xml1 = @__ctrl;
            
            #line 134 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "Xml1";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9019,
                        44,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control29() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    </div>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9063,
                        18,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl2 = this.@__BuildControlLabel4();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl4;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl4 = this.@__BuildControlcmbAccount();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl5 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl6;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl6 = this.@__BuildControlLabel1();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl7 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl8;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl8 = this.@__BuildControlcmbJID();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl9 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl10;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl10 = this.@__BuildControlLabel3();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl11 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl12;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl12 = this.@__BuildControlcmbStage();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl13 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl14;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl14 = this.@__BuildControlLabel2();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl15 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl16;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl16 = this.@__BuildControltxtAID();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl17 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl18;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl18 = this.@__BuildControlImageButton5();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl19;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl19 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl20;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl20 = this.@__BuildControlImageButton1();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl20);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl21;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl21 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl21);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl22;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl22 = this.@__BuildControltxtOrderNotFound();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl22);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl23;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl23 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl23);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Xml @__ctrl24;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl24 = this.@__BuildControlXml1();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl24);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl25;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl25 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl25);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        602,
                        8486,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control30() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9088,
                        4,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl3 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(orderviewer_aspx @__ctrl) {
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.EnableViewState = true;
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.MasterPageFile = "MasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.AddContentTemplate("PageTitle", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlTitle)));
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.AddContentTemplate("UserMaster", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlUserWelcome)));
            
            #line default
            #line hidden
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.AddContentTemplate("PageBody", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.orderviewer_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -317192639;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
