#pragma checksum "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "CEAAE480931F2F3A5BCAA64D60ED169A65E5E703"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class UCrDate {
    
    
    #line 5 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
    protected global::System.Web.UI.WebControls.DropDownList DDLDay;
    
    #line default
    #line hidden
    
    
    #line 6 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
    protected global::System.Web.UI.WebControls.DropDownList DDLMonth;
    
    #line default
    #line hidden
    
    
    #line 7 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
    protected global::System.Web.UI.WebControls.DropDownList DDLYear;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 5 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 406 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 5 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 401 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 397 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 5 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 5 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 5 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class usercontrol_ucrdate_ascx : global::UCrDate {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.usercontrol_ucrdate_ascx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public usercontrol_ucrdate_ascx() {
            
            #line 912304 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx.cs"
            ((global::System.Web.UI.UserControl)(this)).AppRelativeVirtualPath = "~/UserControl/UCrDate.ascx";
            
            #line default
            #line hidden
            if ((global::ASP.usercontrol_ucrdate_ascx.@__initialized == false)) {
                global::ASP.usercontrol_ucrdate_ascx.@__initialized = true;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <table>\r\n        <tr style=\"vertical-align:middle\">\r\n        <td style=\"ver" +
                    "tical-align:middle\">\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        97,
                        115,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=14.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.usercontrol_ucrdate_ascx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.usercontrol_ucrdate_ascx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDDLDay() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.DDLDay = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl.ID = "DDLDay";
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(18D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(36D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        212,
                        95,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        307,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDDLMonth() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.DDLMonth = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl.ID = "DDLMonth";
            
            #line default
            #line hidden
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(18D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(36D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        321,
                        94,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        415,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDDLYear() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 7 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.DDLYear = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 7 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl.ID = "DDLYear";
            
            #line default
            #line hidden
            
            #line 7 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(18D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 7 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(51D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        429,
                        94,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        </td>\r\n    </tr>\r\n    </table>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        523,
                        42,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(usercontrol_ucrdate_ascx @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl2 = this.@__BuildControlDDLDay();
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl3 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl4;
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl4 = this.@__BuildControlDDLMonth();
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl5 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl6;
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl6 = this.@__BuildControlDDLYear();
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__ctrl7 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\WinCVS\ThimeXMLORDER\UserControl\UCrDate.ascx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
        }
        
        #line default
        #line hidden
    }
}
