#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProofSystem.DO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OPS")]
	public partial class AEPSJWDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOPSDetail(OPSDetail instance);
    partial void UpdateOPSDetail(OPSDetail instance);
    partial void DeleteOPSDetail(OPSDetail instance);
    #endregion
		
		
		public AEPSJWDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AEPSJWDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AEPSJWDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AEPSJWDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Setting> Settings
		{
			get
			{
				return this.GetTable<Setting>();
			}
		}
		
		public System.Data.Linq.Table<OPSDetail> OPSDetails
		{
			get
			{
				return this.GetTable<OPSDetail>();
			}
		}
		
		public System.Data.Linq.Table<SINGAPORE_Journal1> SINGAPORE_Journal1s
		{
			get
			{
				return this.GetTable<SINGAPORE_Journal1>();
			}
		}
		
		public System.Data.Linq.Table<ArticleContentReport> ArticleContentReports
		{
			get
			{
				return this.GetTable<ArticleContentReport>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckReViewExistence", IsComposable=true)]
		public System.Nullable<int> CheckReViewExistence([global::System.Data.Linq.Mapping.ParameterAttribute(Name="JID", DbType="VarChar(50)")] string jID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AID", DbType="VarChar(50)")] string aID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jID, aID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_DeleteArticleReviewDetail")]
		public int usp_DeleteArticleReviewDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="JID", DbType="VarChar(50)")] string jID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AID", DbType="VarChar(50)")] string aID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jID, aID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountUploadArticles", IsComposable=true)]
		public System.Nullable<int> CountUploadArticles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLIENT", DbType="VarChar(20)")] string cLIENT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="JID", DbType="VarChar(20)")] string jID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AID", DbType="VarChar(20)")] string aID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Stage", DbType="VarChar(20)")] string stage)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cLIENT, jID, aID, stage).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAuthorEmailFromArticleContentReport", IsComposable=true)]
		public string GetAuthorEmailFromArticleContentReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="JID", DbType="VarChar(50)")] string jID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AID", DbType="VarChar(50)")] string aID)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jID, aID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ToCheckArticleContentReport", IsComposable=true)]
		public System.Nullable<int> ToCheckArticleContentReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="JID", DbType="VarChar(50)")] string jID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jID).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Settings")]
	public partial class Setting
	{
		
		private string _CustomerName;
		
		private string _StageName;
		
		private string _DistillerPath;
		
		private string _JobOptions;
		
		public Setting()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(100)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StageName", DbType="NVarChar(100)")]
		public string StageName
		{
			get
			{
				return this._StageName;
			}
			set
			{
				if ((this._StageName != value))
				{
					this._StageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistillerPath", DbType="NVarChar(100)")]
		public string DistillerPath
		{
			get
			{
				return this._DistillerPath;
			}
			set
			{
				if ((this._DistillerPath != value))
				{
					this._DistillerPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobOptions", DbType="NVarChar(100)")]
		public string JobOptions
		{
			get
			{
				return this._JobOptions;
			}
			set
			{
				if ((this._JobOptions != value))
				{
					this._JobOptions = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OPSDetails")]
	public partial class OPSDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OPSID;
		
		private string _Jid;
		
		private string _Client;
		
		private string _Category;
		
		private string _Jname;
		
		private string _Peditor;
		
		private string _Designation;
		
		private string _Pe_email;
		
		private string _PRMaill;
		
		private string _CCMail;
		
		private string _Role;
		
		private string _BccMail;
		
		private string _FromMail;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Address;
		
		private string _TemplateFileName;
		
		private string _final_cc;
		
		private string _PrinterMail;
		
		private string _PrinterCC;
		
		private string _FailEmail;
		
		private string _PrinterName;
		
		private string _Reminder;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private string _ModifiedBy;
		
		private string _Remarks;
		
		private string _InternalPEName;
		
		private string _InternalPEmail;
		
		private int _ProofExpired;
		
		private string _BatchMail;
		
		private string _ReviewerEmail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOPSIDChanging(int value);
    partial void OnOPSIDChanged();
    partial void OnJidChanging(string value);
    partial void OnJidChanged();
    partial void OnClientChanging(string value);
    partial void OnClientChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnJnameChanging(string value);
    partial void OnJnameChanged();
    partial void OnPeditorChanging(string value);
    partial void OnPeditorChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnPe_emailChanging(string value);
    partial void OnPe_emailChanged();
    partial void OnPRMaillChanging(string value);
    partial void OnPRMaillChanged();
    partial void OnCCMailChanging(string value);
    partial void OnCCMailChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnBccMailChanging(string value);
    partial void OnBccMailChanged();
    partial void OnFromMailChanging(string value);
    partial void OnFromMailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnTemplateFileNameChanging(string value);
    partial void OnTemplateFileNameChanged();
    partial void Onfinal_ccChanging(string value);
    partial void Onfinal_ccChanged();
    partial void OnPrinterMailChanging(string value);
    partial void OnPrinterMailChanged();
    partial void OnPrinterCCChanging(string value);
    partial void OnPrinterCCChanged();
    partial void OnFailEmailChanging(string value);
    partial void OnFailEmailChanged();
    partial void OnPrinterNameChanging(string value);
    partial void OnPrinterNameChanged();
    partial void OnReminderChanging(string value);
    partial void OnReminderChanged();
    partial void OnDateModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateModifiedChanged();
    partial void OnModifiedByChanging(string value);
    partial void OnModifiedByChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnInternalPENameChanging(string value);
    partial void OnInternalPENameChanged();
    partial void OnInternalPEmailChanging(string value);
    partial void OnInternalPEmailChanged();
    partial void OnProofExpiredChanging(int value);
    partial void OnProofExpiredChanged();
    partial void OnBatchMailChanging(string value);
    partial void OnBatchMailChanged();
    partial void OnReviewerEmailChanging(string value);
    partial void OnReviewerEmailChanged();
    #endregion
		
		public OPSDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPSID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OPSID
		{
			get
			{
				return this._OPSID;
			}
			set
			{
				if ((this._OPSID != value))
				{
					this.OnOPSIDChanging(value);
					this.SendPropertyChanging();
					this._OPSID = value;
					this.SendPropertyChanged("OPSID");
					this.OnOPSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jid", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Jid
		{
			get
			{
				return this._Jid;
			}
			set
			{
				if ((this._Jid != value))
				{
					this.OnJidChanging(value);
					this.SendPropertyChanging();
					this._Jid = value;
					this.SendPropertyChanged("Jid");
					this.OnJidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="VarChar(50)")]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this.OnClientChanging(value);
					this.SendPropertyChanging();
					this._Client = value;
					this.SendPropertyChanged("Client");
					this.OnClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jname", DbType="NVarChar(100)")]
		public string Jname
		{
			get
			{
				return this._Jname;
			}
			set
			{
				if ((this._Jname != value))
				{
					this.OnJnameChanging(value);
					this.SendPropertyChanging();
					this._Jname = value;
					this.SendPropertyChanged("Jname");
					this.OnJnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peditor", DbType="NVarChar(50)")]
		public string Peditor
		{
			get
			{
				return this._Peditor;
			}
			set
			{
				if ((this._Peditor != value))
				{
					this.OnPeditorChanging(value);
					this.SendPropertyChanging();
					this._Peditor = value;
					this.SendPropertyChanged("Peditor");
					this.OnPeditorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(50)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pe_email", DbType="NVarChar(255)")]
		public string Pe_email
		{
			get
			{
				return this._Pe_email;
			}
			set
			{
				if ((this._Pe_email != value))
				{
					this.OnPe_emailChanging(value);
					this.SendPropertyChanging();
					this._Pe_email = value;
					this.SendPropertyChanged("Pe_email");
					this.OnPe_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRMaill", DbType="NVarChar(250)")]
		public string PRMaill
		{
			get
			{
				return this._PRMaill;
			}
			set
			{
				if ((this._PRMaill != value))
				{
					this.OnPRMaillChanging(value);
					this.SendPropertyChanging();
					this._PRMaill = value;
					this.SendPropertyChanged("PRMaill");
					this.OnPRMaillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCMail", DbType="NVarChar(255)")]
		public string CCMail
		{
			get
			{
				return this._CCMail;
			}
			set
			{
				if ((this._CCMail != value))
				{
					this.OnCCMailChanging(value);
					this.SendPropertyChanging();
					this._CCMail = value;
					this.SendPropertyChanged("CCMail");
					this.OnCCMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(200)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BccMail", DbType="NVarChar(255)")]
		public string BccMail
		{
			get
			{
				return this._BccMail;
			}
			set
			{
				if ((this._BccMail != value))
				{
					this.OnBccMailChanging(value);
					this.SendPropertyChanging();
					this._BccMail = value;
					this.SendPropertyChanged("BccMail");
					this.OnBccMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromMail", DbType="NVarChar(255)")]
		public string FromMail
		{
			get
			{
				return this._FromMail;
			}
			set
			{
				if ((this._FromMail != value))
				{
					this.OnFromMailChanging(value);
					this.SendPropertyChanging();
					this._FromMail = value;
					this.SendPropertyChanged("FromMail");
					this.OnFromMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(100)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(100)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(150)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateFileName", DbType="NVarChar(150)")]
		public string TemplateFileName
		{
			get
			{
				return this._TemplateFileName;
			}
			set
			{
				if ((this._TemplateFileName != value))
				{
					this.OnTemplateFileNameChanging(value);
					this.SendPropertyChanging();
					this._TemplateFileName = value;
					this.SendPropertyChanged("TemplateFileName");
					this.OnTemplateFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_cc", DbType="NVarChar(100)")]
		public string final_cc
		{
			get
			{
				return this._final_cc;
			}
			set
			{
				if ((this._final_cc != value))
				{
					this.Onfinal_ccChanging(value);
					this.SendPropertyChanging();
					this._final_cc = value;
					this.SendPropertyChanged("final_cc");
					this.Onfinal_ccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrinterMail", DbType="NVarChar(50)")]
		public string PrinterMail
		{
			get
			{
				return this._PrinterMail;
			}
			set
			{
				if ((this._PrinterMail != value))
				{
					this.OnPrinterMailChanging(value);
					this.SendPropertyChanging();
					this._PrinterMail = value;
					this.SendPropertyChanged("PrinterMail");
					this.OnPrinterMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrinterCC", DbType="NVarChar(50)")]
		public string PrinterCC
		{
			get
			{
				return this._PrinterCC;
			}
			set
			{
				if ((this._PrinterCC != value))
				{
					this.OnPrinterCCChanging(value);
					this.SendPropertyChanging();
					this._PrinterCC = value;
					this.SendPropertyChanged("PrinterCC");
					this.OnPrinterCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailEmail", DbType="VarChar(250)")]
		public string FailEmail
		{
			get
			{
				return this._FailEmail;
			}
			set
			{
				if ((this._FailEmail != value))
				{
					this.OnFailEmailChanging(value);
					this.SendPropertyChanging();
					this._FailEmail = value;
					this.SendPropertyChanged("FailEmail");
					this.OnFailEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrinterName", DbType="NVarChar(50)")]
		public string PrinterName
		{
			get
			{
				return this._PrinterName;
			}
			set
			{
				if ((this._PrinterName != value))
				{
					this.OnPrinterNameChanging(value);
					this.SendPropertyChanging();
					this._PrinterName = value;
					this.SendPropertyChanged("PrinterName");
					this.OnPrinterNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reminder", DbType="NVarChar(50)")]
		public string Reminder
		{
			get
			{
				return this._Reminder;
			}
			set
			{
				if ((this._Reminder != value))
				{
					this.OnReminderChanging(value);
					this.SendPropertyChanging();
					this._Reminder = value;
					this.SendPropertyChanged("Reminder");
					this.OnReminderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="NVarChar(50)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(500)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalPEName", DbType="NVarChar(255)")]
		public string InternalPEName
		{
			get
			{
				return this._InternalPEName;
			}
			set
			{
				if ((this._InternalPEName != value))
				{
					this.OnInternalPENameChanging(value);
					this.SendPropertyChanging();
					this._InternalPEName = value;
					this.SendPropertyChanged("InternalPEName");
					this.OnInternalPENameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalPEmail", DbType="NVarChar(255)")]
		public string InternalPEmail
		{
			get
			{
				return this._InternalPEmail;
			}
			set
			{
				if ((this._InternalPEmail != value))
				{
					this.OnInternalPEmailChanging(value);
					this.SendPropertyChanging();
					this._InternalPEmail = value;
					this.SendPropertyChanged("InternalPEmail");
					this.OnInternalPEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProofExpired", DbType="Int NOT NULL")]
		public int ProofExpired
		{
			get
			{
				return this._ProofExpired;
			}
			set
			{
				if ((this._ProofExpired != value))
				{
					this.OnProofExpiredChanging(value);
					this.SendPropertyChanging();
					this._ProofExpired = value;
					this.SendPropertyChanged("ProofExpired");
					this.OnProofExpiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatchMail", DbType="VarChar(MAX)")]
		public string BatchMail
		{
			get
			{
				return this._BatchMail;
			}
			set
			{
				if ((this._BatchMail != value))
				{
					this.OnBatchMailChanging(value);
					this.SendPropertyChanging();
					this._BatchMail = value;
					this.SendPropertyChanged("BatchMail");
					this.OnBatchMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewerEmail", DbType="NVarChar(MAX)")]
		public string ReviewerEmail
		{
			get
			{
				return this._ReviewerEmail;
			}
			set
			{
				if ((this._ReviewerEmail != value))
				{
					this.OnReviewerEmailChanging(value);
					this.SendPropertyChanging();
					this._ReviewerEmail = value;
					this.SendPropertyChanged("ReviewerEmail");
					this.OnReviewerEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SINGAPORE_Journal1")]
	public partial class SINGAPORE_Journal1
	{
		
		private string _Jid;
		
		private string _Category;
		
		private string _Jname;
		
		private string _Peditor;
		
		private string _Designation;
		
		private string _Pe_email;
		
		private string _Ccmail;
		
		private string _BccMail;
		
		private string _FromMail;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Address;
		
		private string _TemplateFileName;
		
		private string _final_cc;
		
		private string _PrinterMail;
		
		private string _PrinterCC;
		
		private string _FailEmail;
		
		private string _PrinterName;
		
		private string _Reminder;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private string _ModifiedBy;
		
		private string _Remarks;
		
		private string _InternalPEName;
		
		private string _InternalPEmail;
		
		private string _EarlyView;
		
		public SINGAPORE_Journal1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jid", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Jid
		{
			get
			{
				return this._Jid;
			}
			set
			{
				if ((this._Jid != value))
				{
					this._Jid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jname", DbType="NVarChar(100)")]
		public string Jname
		{
			get
			{
				return this._Jname;
			}
			set
			{
				if ((this._Jname != value))
				{
					this._Jname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peditor", DbType="NVarChar(50)")]
		public string Peditor
		{
			get
			{
				return this._Peditor;
			}
			set
			{
				if ((this._Peditor != value))
				{
					this._Peditor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(50)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this._Designation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pe_email", DbType="NVarChar(255)")]
		public string Pe_email
		{
			get
			{
				return this._Pe_email;
			}
			set
			{
				if ((this._Pe_email != value))
				{
					this._Pe_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ccmail", DbType="NVarChar(255)")]
		public string Ccmail
		{
			get
			{
				return this._Ccmail;
			}
			set
			{
				if ((this._Ccmail != value))
				{
					this._Ccmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BccMail", DbType="NVarChar(255)")]
		public string BccMail
		{
			get
			{
				return this._BccMail;
			}
			set
			{
				if ((this._BccMail != value))
				{
					this._BccMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromMail", DbType="NVarChar(255)")]
		public string FromMail
		{
			get
			{
				return this._FromMail;
			}
			set
			{
				if ((this._FromMail != value))
				{
					this._FromMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(100)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(100)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateFileName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string TemplateFileName
		{
			get
			{
				return this._TemplateFileName;
			}
			set
			{
				if ((this._TemplateFileName != value))
				{
					this._TemplateFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_cc", DbType="NVarChar(100)")]
		public string final_cc
		{
			get
			{
				return this._final_cc;
			}
			set
			{
				if ((this._final_cc != value))
				{
					this._final_cc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrinterMail", DbType="NVarChar(50)")]
		public string PrinterMail
		{
			get
			{
				return this._PrinterMail;
			}
			set
			{
				if ((this._PrinterMail != value))
				{
					this._PrinterMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrinterCC", DbType="NVarChar(50)")]
		public string PrinterCC
		{
			get
			{
				return this._PrinterCC;
			}
			set
			{
				if ((this._PrinterCC != value))
				{
					this._PrinterCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailEmail", DbType="NVarChar(50)")]
		public string FailEmail
		{
			get
			{
				return this._FailEmail;
			}
			set
			{
				if ((this._FailEmail != value))
				{
					this._FailEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrinterName", DbType="NVarChar(50)")]
		public string PrinterName
		{
			get
			{
				return this._PrinterName;
			}
			set
			{
				if ((this._PrinterName != value))
				{
					this._PrinterName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reminder", DbType="NVarChar(50)")]
		public string Reminder
		{
			get
			{
				return this._Reminder;
			}
			set
			{
				if ((this._Reminder != value))
				{
					this._Reminder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this._DateModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="NVarChar(50)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(500)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalPEName", DbType="NVarChar(255)")]
		public string InternalPEName
		{
			get
			{
				return this._InternalPEName;
			}
			set
			{
				if ((this._InternalPEName != value))
				{
					this._InternalPEName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalPEmail", DbType="NVarChar(255)")]
		public string InternalPEmail
		{
			get
			{
				return this._InternalPEmail;
			}
			set
			{
				if ((this._InternalPEmail != value))
				{
					this._InternalPEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EarlyView", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EarlyView
		{
			get
			{
				return this._EarlyView;
			}
			set
			{
				if ((this._EarlyView != value))
				{
					this._EarlyView = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ArticleContentReport")]
	public partial class ArticleContentReport
	{
		
		private int _ACRID;
		
		private string _AID;
		
		private string _CorAuthor;
		
		private string _CorEmail;
		
		public ArticleContentReport()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACRID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ACRID
		{
			get
			{
				return this._ACRID;
			}
			set
			{
				if ((this._ACRID != value))
				{
					this._ACRID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AID", DbType="VarChar(50)")]
		public string AID
		{
			get
			{
				return this._AID;
			}
			set
			{
				if ((this._AID != value))
				{
					this._AID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorAuthor", DbType="NVarChar(50)")]
		public string CorAuthor
		{
			get
			{
				return this._CorAuthor;
			}
			set
			{
				if ((this._CorAuthor != value))
				{
					this._CorAuthor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorEmail", DbType="NVarChar(50)")]
		public string CorEmail
		{
			get
			{
				return this._CorEmail;
			}
			set
			{
				if ((this._CorEmail != value))
				{
					this._CorEmail = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
