//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.18408")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_vo5ncuit {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_vo5ncuit() {
        }
        
        static object Create_ASP_fullmaster_master() {
            return new ASP.fullmaster_master();
        }
        
        static object Create_ASP_ordercreator_aspx() {
            return new ASP.ordercreator_aspx();
        }
        
        static object Create_ASP_orderviewer_aspx() {
            return new ASP.orderviewer_aspx();
        }
        
        static object Create_ASP_emcorder_aspx() {
            return new ASP.emcorder_aspx();
        }
    }
}
