//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.18408")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_4a5ivd3b {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_4a5ivd3b() {
        }
        
        static object Create_ASP_masterpage_master() {
            return new ASP.masterpage_master();
        }
        
        static object Create_ASP_orderdetails_aspx() {
            return new ASP.orderdetails_aspx();
        }
        
        static object Create_ASP_updateorder_aspx() {
            return new ASP.updateorder_aspx();
        }
        
        static object Create_ASP_home_aspx() {
            return new ASP.home_aspx();
        }
        
        static object Create_ASP_viewlog_aspx() {
            return new ASP.viewlog_aspx();
        }
    }
}
