#pragma checksum "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "72B80F212F062D8BC04E12E0BB0C25A58330EBD0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class OrderViewer : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label lblUser;
    
    #line default
    #line hidden
    
    
    #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label Label4;
    
    #line default
    #line hidden
    
    
    #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.DropDownList cmbAccount;
    
    #line default
    #line hidden
    
    
    #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label Label1;
    
    #line default
    #line hidden
    
    
    #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.DropDownList cmbJID;
    
    #line default
    #line hidden
    
    
    #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label Label3;
    
    #line default
    #line hidden
    
    
    #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.DropDownList cmbStage;
    
    #line default
    #line hidden
    
    
    #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label Label2;
    
    #line default
    #line hidden
    
    
    #line 97 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtAID;
    
    #line default
    #line hidden
    
    
    #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.ImageButton ImageButton5;
    
    #line default
    #line hidden
    
    
    #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.ImageButton ImageButton1;
    
    #line default
    #line hidden
    
    
    #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Label txtOrderNotFound;
    
    #line default
    #line hidden
    
    
    #line 134 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.WebControls.Xml Xml1;
    
    #line default
    #line hidden
    
    
    #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 284 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 281 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 283 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 279 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 277 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 276 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 278 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 275 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 282 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 289 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 280 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 285 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class orderviewer_aspx : global::OrderViewer, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public orderviewer_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/OrderViewer.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.orderviewer_aspx.@__initialized == false)) {
                global::ASP.orderviewer_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/OrderViewer.aspx";
                dependencies[1] = "~/OrderViewer.aspx.cs";
                dependencies[2] = "~/MasterPage.master";
                dependencies[3] = "~/MasterPage.master.cs";
                global::ASP.orderviewer_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.orderviewer_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTitle(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Welcome to XML Order Creation and Integration Application"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblUser() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblUser = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "lblUser";
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "";
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Size = global::System.Web.UI.WebControls.FontUnit.Small;
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlUserWelcome(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<span id=\"aa\"></span> "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControllblUser();
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel4() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "Label4";
            
            #line default
            #line hidden
            
            #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "Account";
            
            #line default
            #line hidden
            
            #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 27 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Gray;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 30 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 30 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "JWUSA";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control4() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 31 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 31 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "JWUK";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control5() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 32 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 32 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "JWVCH";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlcmbAccount() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.cmbAccount = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "cmbAccount";
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative");
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(150D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.@__BuildControl__control2(@__ctrl.Items);
            
            #line default
            #line hidden
            
            #line 29 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.cmbAccount_SelectedIndexChanged);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "Label1";
            
            #line default
            #line hidden
            
            #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "JID";
            
            #line default
            #line hidden
            
            #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 47 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Gray;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlcmbJID() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.cmbJID = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "cmbJID";
            
            #line default
            #line hidden
            
            #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative");
            
            #line default
            #line hidden
            
            #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(102D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 50 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.cmbJID_SelectedIndexChanged);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel3() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "Label3";
            
            #line default
            #line hidden
            
            #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "STAGE";
            
            #line default
            #line hidden
            
            #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 67 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Gray;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control7() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 71 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 71 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "Fresh";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control8() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 72 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 72 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "MCE";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control9() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 73 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 73 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "Revise";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control10() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 74 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 74 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "FAX";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control11() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 75 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 75 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "SGML";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control12() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 76 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 76 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "Web";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control13() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 77 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 77 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "Printer";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control6(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl2 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl3 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl4 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl5;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl5 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl6;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl6 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl7;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl7 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlcmbStage() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.cmbStage = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "cmbStage";
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative");
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(155D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 70 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.@__BuildControl__control6(@__ctrl.Items);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel2() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "Label2";
            
            #line default
            #line hidden
            
            #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Text = "AID/ISSUE";
            
            #line default
            #line hidden
            
            #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 94 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Gray;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtAID() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 97 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtAID = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 97 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "txtAID";
            
            #line default
            #line hidden
            
            #line 97 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControlImageButton5() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            this.ImageButton5 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "ImageButton5";
            
            #line default
            #line hidden
            
            #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative; z-index: 100;");
            
            #line default
            #line hidden
            
            #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ImageUrl = "button_view.gif";
            
            #line default
            #line hidden
            
            #line 112 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Click += new System.Web.UI.ImageClickEventHandler(this.ImageButton5_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControlImageButton1() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            this.ImageButton1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "ImageButton1";
            
            #line default
            #line hidden
            
            #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position: relative");
            
            #line default
            #line hidden
            
            #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ImageUrl = "btnhome.gif";
            
            #line default
            #line hidden
            
            #line 120 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Click += new System.Web.UI.ImageClickEventHandler(this.ImageButton1_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControltxtOrderNotFound() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.txtOrderNotFound = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "txtOrderNotFound";
            
            #line default
            #line hidden
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "position:relative");
            
            #line default
            #line hidden
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(723D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 131 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.OrangeRed;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Xml @__BuildControlXml1() {
            global::System.Web.UI.WebControls.Xml @__ctrl;
            
            #line 134 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Xml();
            
            #line default
            #line hidden
            this.Xml1 = @__ctrl;
            
            #line 134 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "Xml1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(9795, 1067, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControlLabel4();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                    " +
                        "        <td style=\"width: 39px\">                                                " +
                        ""));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl2 = this.@__BuildControlcmbAccount();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(10862, 813, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl3;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl3 = this.@__BuildControlLabel1();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                    " +
                        "        <td style=\"width: 39px; height: 25px;\">\r\n                               " +
                        "                 "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl4;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl4 = this.@__BuildControlcmbJID();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(11675, 868, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl5;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl5 = this.@__BuildControlLabel3();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                    " +
                        "        <td style=\"width: 42px; height: 15px;\">\r\n                               " +
                        "             "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl6;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl6 = this.@__BuildControlcmbStage();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(12543, 798, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl7;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl7 = this.@__BuildControlLabel2();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                    " +
                        "        <td style=\"width: 28px\">\r\n                                              " +
                        "  "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl8 = this.@__BuildControltxtAID();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(13341, 852, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl9;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl9 = this.@__BuildControlImageButton5();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(14193, 471, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl10;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl10 = this.@__BuildControlImageButton1();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(14664, 462, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl11;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl11 = this.@__BuildControltxtOrderNotFound();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n            </tr>\r\n        </table>\r\n\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Xml @__ctrl12;
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl12 = this.@__BuildControlXml1();
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 10 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl1;
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl1 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(orderviewer_aspx @__ctrl) {
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.EnableViewState = true;
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__ctrl.MasterPageFile = "MasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.AddContentTemplate("PageTitle", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlTitle)));
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.AddContentTemplate("UserMaster", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlUserWelcome)));
            
            #line default
            #line hidden
            
            #line 6 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            this.AddContentTemplate("PageBody", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\WinCVS\ThimeXMLORDER\OrderViewer.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.orderviewer_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.orderviewer_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -317192639;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
