#pragma checksum "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E30F3F7686963DD5161A99E0B1A1F1113264AF56"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class LoginReport : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 8 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
    protected global::System.Web.UI.WebControls.Button Excel;
    
    #line default
    #line hidden
    
    
    #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
    protected global::System.Web.UI.WebControls.GridView GridView1;
    
    #line default
    #line hidden
    
    
    #line 28 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
    protected global::System.Web.UI.WebControls.SqlDataSource TISDataSource;
    
    #line default
    #line hidden
    
    
    #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 284 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 281 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 283 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 279 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 277 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 4 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 276 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 4 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 278 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 275 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 1 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 282 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 4 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 289 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 280 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 285 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class loginreport_aspx : global::LoginReport, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public loginreport_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/LoginReport.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.loginreport_aspx.@__initialized == false)) {
                global::ASP.loginreport_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[6];
                dependencies[0] = "~/LoginReport.aspx";
                dependencies[1] = "~/FullMaster.master";
                dependencies[2] = "~/FullMaster.master.cs";
                dependencies[3] = "~/MasterPage.master";
                dependencies[4] = "~/MasterPage.master.cs";
                dependencies[5] = "~/LoginReport.aspx.cs";
                global::ASP.loginreport_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.loginreport_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlExcel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 8 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.Excel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 8 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.ID = "Excel";
            
            #line default
            #line hidden
            
            #line 8 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.Text = "SaveExcel";
            
            #line default
            #line hidden
            
            #line 8 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.Click += new System.EventHandler(this.Excel_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(0, 0, 102)));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control3(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.BackColor = global::System.Drawing.Color.White;
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(0, 0, 102)));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control4(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Left;
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.BackColor = global::System.Drawing.Color.White;
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(0, 0, 102)));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control5(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(102, 153, 153)));
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.White;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control6(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(0, 102, 153)));
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.White;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlGridView1() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            
            #line default
            #line hidden
            this.GridView1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.ID = "GridView1";
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "z-index: 100; position: relative;");
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.AllowSorting = true;
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            this.@__BuildControl__control2(@__ctrl.RowStyle);
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            this.@__BuildControl__control3(@__ctrl.FooterStyle);
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            this.@__BuildControl__control4(@__ctrl.PagerStyle);
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            this.@__BuildControl__control5(@__ctrl.SelectedRowStyle);
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            this.@__BuildControl__control6(@__ctrl.HeaderStyle);
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.Sorted += new System.EventHandler(this.GridView1_Sorted);
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.Sorting += new System.Web.UI.WebControls.GridViewSortEventHandler(this.GridView1_Sorting);
            
            #line default
            #line hidden
            
            #line 14 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.RowDataBound += new System.Web.UI.WebControls.GridViewRowEventHandler(this.GridView1_RowDataBound);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.SqlDataSource @__BuildControlTISDataSource() {
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl;
            
            #line 28 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.SqlDataSource();
            
            #line default
            #line hidden
            this.TISDataSource = @__ctrl;
            
            #line 28 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.ID = "TISDataSource";
            
            #line default
            #line hidden
            
            #line 28 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.SelectCommand = "SELECT * FROM JW_PTS WHERE JW_PTS.STAGE = \'FRESH\' AND STATUS = \'OPEN\'";
            
            #line default
            #line hidden
            @__ctrl.ConnectionString = global::System.Convert.ToString(System.Web.Compilation.ConnectionStringsExpressionBuilder.GetConnectionString("ConnectionString"), global::System.Globalization.CultureInfo.CurrentCulture);
            @__ctrl.ProviderName = global::System.Convert.ToString(System.Web.Compilation.ConnectionStringsExpressionBuilder.GetConnectionStringProviderName("ConnectionString"), global::System.Globalization.CultureInfo.CurrentCulture);
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n  <div>\r\n  <table width=\"100%\"><tr>\r\n  <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl1;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl1 = this.@__BuildControlExcel();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n  \r\n  </tr></table>\r\n    <hr />\r\n    \r\n\r\n "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl2;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl2 = this.@__BuildControlGridView1();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl3;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl3 = this.@__BuildControlTISDataSource();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n      &nbsp;&nbsp;\r\n    </div>\r\n"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlbody(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n  "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl1;
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl1 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(loginreport_aspx @__ctrl) {
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.MasterPageFile = "FullMaster.master";
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            @__ctrl.Title = "Untitled Page";
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx"
            this.AddContentTemplate("ContentBody", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlbody)));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\WinCVS\ThimeXMLORDER\LoginReport.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.loginreport_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.loginreport_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 283287649;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
