#pragma checksum "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4DF10097BEC4BF0E446DED98646735DED64A0B4B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ChangePassword : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 9 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.Label Label3;
    
    #line default
    #line hidden
    
    
    #line 11 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.TextBox LoginID;
    
    #line default
    #line hidden
    
    
    #line 15 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.Label lb1;
    
    #line default
    #line hidden
    
    
    #line 17 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.TextBox Password;
    
    #line default
    #line hidden
    
    
    #line 20 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.Label Label1;
    
    #line default
    #line hidden
    
    
    #line 22 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.TextBox NewPassword;
    
    #line default
    #line hidden
    
    
    #line 26 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.Label Label2;
    
    #line default
    #line hidden
    
    
    #line 28 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.TextBox ConfirmPassword;
    
    #line default
    #line hidden
    
    
    #line 32 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.Button ChangePasswordBtn;
    
    #line default
    #line hidden
    
    
    #line 34 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.Button Cancel;
    
    #line default
    #line hidden
    
    
    #line 37 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.Label Err;
    
    #line default
    #line hidden
    
    
    #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 284 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 281 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 283 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 279 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 277 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 2 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 276 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 2 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 278 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 275 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 1 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 282 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 2 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 289 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 280 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 285 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class changepassword_aspx : global::ChangePassword, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public changepassword_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/ChangePassword.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.changepassword_aspx.@__initialized == false)) {
                global::ASP.changepassword_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[6];
                dependencies[0] = "~/ChangePassword.aspx";
                dependencies[1] = "~/FullMaster.master";
                dependencies[2] = "~/FullMaster.master.cs";
                dependencies[3] = "~/MasterPage.master";
                dependencies[4] = "~/MasterPage.master.cs";
                dependencies[5] = "~/ChangePassword.aspx.cs";
                global::ASP.changepassword_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.changepassword_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTitle(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 2 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Change Password"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlUserLogin(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("New User"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel3() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 9 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 9 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "Label3";
            
            #line default
            #line hidden
            
            #line 9 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(80, 124, 209)));
            
            #line default
            #line hidden
            
            #line 9 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Font.Names = new string[] {
                    "Verdana"};
            
            #line default
            #line hidden
            
            #line 9 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Font.Size = global::System.Web.UI.WebControls.FontUnit.Smaller;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 9 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Enter Your Login: "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlLoginID() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 11 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.LoginID = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 11 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "LoginID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllb1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 15 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lb1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 15 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "lb1";
            
            #line default
            #line hidden
            
            #line 15 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(80, 124, 209)));
            
            #line default
            #line hidden
            
            #line 15 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Font.Names = new string[] {
                    "Verdana"};
            
            #line default
            #line hidden
            
            #line 15 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Font.Size = global::System.Web.UI.WebControls.FontUnit.Smaller;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 15 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Enter Your Old Password: "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlPassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 17 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.Password = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 17 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "Password";
            
            #line default
            #line hidden
            
            #line 17 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 20 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 20 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "Label1";
            
            #line default
            #line hidden
            
            #line 20 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Font.Names = new string[] {
                    "Verdana"};
            
            #line default
            #line hidden
            
            #line 20 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Font.Size = global::System.Web.UI.WebControls.FontUnit.Smaller;
            
            #line default
            #line hidden
            
            #line 20 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(80, 124, 209)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 20 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Enter Your New Password: "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlNewPassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 22 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.NewPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 22 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "NewPassword";
            
            #line default
            #line hidden
            
            #line 22 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel2() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 26 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 26 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "Label2";
            
            #line default
            #line hidden
            
            #line 26 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Font.Names = new string[] {
                    "Verdana"};
            
            #line default
            #line hidden
            
            #line 26 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Font.Size = global::System.Web.UI.WebControls.FontUnit.Smaller;
            
            #line default
            #line hidden
            
            #line 26 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(80, 124, 209)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 26 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Confirm Your New Password: "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlConfirmPassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 28 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.ConfirmPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 28 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "ConfirmPassword";
            
            #line default
            #line hidden
            
            #line 28 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlChangePasswordBtn() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 32 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.ChangePasswordBtn = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 32 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "ChangePasswordBtn";
            
            #line default
            #line hidden
            
            #line 32 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Text = "Change Password";
            
            #line default
            #line hidden
            
            #line 32 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Click += new System.EventHandler(this.ChangePasswordBtn_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 34 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.Cancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 34 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "Cancel";
            
            #line default
            #line hidden
            
            #line 34 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Text = "Cancel";
            
            #line default
            #line hidden
            
            #line 34 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Click += new System.EventHandler(this.Cancel_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlErr() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 37 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Err = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 37 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "Err";
            
            #line default
            #line hidden
            
            #line 37 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Font.Names = new string[] {
                    "Verdana"};
            
            #line default
            #line hidden
            
            #line 37 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Font.Size = new System.Web.UI.WebControls.FontUnit(new System.Web.UI.WebControls.Unit(0.800000011920929D, global::System.Web.UI.WebControls.UnitType.Em));
            
            #line default
            #line hidden
            
            #line 37 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<table align=\"center\">\r\n<tr>\r\n<td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControlLabel3();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n<td style=\"width: 165px\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl2 = this.@__BuildControlLoginID();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n<td style=\"width: 22px\"></td>\r\n</tr>\r\n<tr>\r\n<td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl3;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl3 = this.@__BuildControllb1();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n<td style=\"width: 165px\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl4 = this.@__BuildControlPassword();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n<td style=\"width: 22px\"></tr>\r\n<tr>\r\n<td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl5;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl5 = this.@__BuildControlLabel1();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n<td style=\"width: 165px\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl6 = this.@__BuildControlNewPassword();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n<td style=\"width: 22px\"></td>\r\n</tr>\r\n<tr>\r\n<td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl7;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl7 = this.@__BuildControlLabel2();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n<td style=\"width: 165px\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl8 = this.@__BuildControlConfirmPassword();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n<td style=\"width: 22px\"></td>\r\n</tr>\r\n<tr>\r\n<td align=\"center\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl9;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl9 = this.@__BuildControlChangePasswordBtn();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</td>\r\n<td style=\"width: 165px\" align=\"center\" colspan=2>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl10;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl10 = this.@__BuildControlCancel();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n</tr>\r\n<tr>\r\n<td colspan=3>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl11;
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl11 = this.@__BuildControlErr();
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 5 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n</tr>\r\n</table>\r\n\r\n\r\n\r\n"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlOrderContent(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl1;
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(changepassword_aspx @__ctrl) {
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.MasterPageFile = "FullMaster.master";
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__ctrl.Title = "Change Password";
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 2 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            this.AddContentTemplate("TitleThis", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlTitle)));
            
            #line default
            #line hidden
            
            #line 3 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            this.AddContentTemplate("UserThis", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlUserLogin)));
            
            #line default
            #line hidden
            
            #line 4 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            this.AddContentTemplate("ContentBody", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlOrderContent)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\WinCVS\ThimeXMLORDER\ChangePassword.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.changepassword_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.changepassword_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1643418609;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
