<?xml version="1.0" encoding="utf-8"?><Database Name="LWW" Class="LWWDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.16.0.61;Initial Catalog=LWW;User ID=sa" SettingsObjectName="LWWeProof.Properties.Settings" SettingsPropertyName="LWWConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DATASETHISTORY" Member="DATASETHISTORies">
    <Type Name="DATASETHISTORY">
      <Column Name="RNO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="JID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STAGE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPLOADDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LWWWIP" Member="LWWWIPs">
    <Type Name="LWWWIP">
      <Column Name="SNO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOWNLOADSTATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TASKNAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DUEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RECEIVEDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SENDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MSS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAGES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FIGCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOI" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CLIENT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STAGE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SERVERIP" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VOL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ISSUE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GOXML" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="METADATAXML" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="GOXMLPATH" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MessageDetail" Member="MessageDetails">
    <Type Name="MessageDetail">
      <Column Name="MsgID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Client" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Stage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MsgDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JIDAID" Type="System.String" DbType="VarChar(100) NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.UPLOADHISTORY" Member="UPLOADHISTORies">
    <Type Name="UPLOADHISTORY">
      <Column Name="RNO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FILENAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UPLOAD_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPLOAD_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.usp_GetInprocessMessageDetail" Method="usp_GetInprocessMessageDetail">
    <ElementType Name="usp_GetInprocessMessageDetailResult">
      <Column Name="MsgID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Client" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Stage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MsgDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JIDAID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_InsertDatasetHistory" Method="usp_InsertDatasetHistory">
    <Parameter Name="JID" Parameter="jID" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="AID" Parameter="aID" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Stage" Parameter="stage" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_InsertMessageDetail" Method="usp_InsertMessageDetail">
    <Parameter Name="Client" Parameter="client" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="JID" Parameter="jID" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="AID" Parameter="aID" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Stage" Parameter="stage" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="IP" Parameter="iP" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_GetDatasetHistoryRNO" Method="usp_GetDatasetHistoryRNO" IsComposable="true">
    <Parameter Name="JID" Parameter="jID" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="AID" Parameter="aID" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Stage" Parameter="stage" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_UpdateMessageStatus" Method="usp_UpdateMessageStatus">
    <Parameter Name="MsgID" Parameter="msgID" Type="System.Int32" DbType="Int" />
    <Parameter Name="WIPRno" Parameter="wIPRno" Type="System.Int32" DbType="Int" />
    <Parameter Name="Pages" Parameter="pages" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_GetAIDDetails" Method="usp_GetAIDDetails">
    <Parameter Name="AID" Parameter="aID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STAGE" Parameter="sTAGE" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="usp_GetAIDDetailsResult">
      <Column Name="SNO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TASKNAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="STAGE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GOXML" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="METADATAXML" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SubmissionXML" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>