#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWWeProof
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LWW")]
	public partial class LWWDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDATASETHISTORY(DATASETHISTORY instance);
    partial void UpdateDATASETHISTORY(DATASETHISTORY instance);
    partial void DeleteDATASETHISTORY(DATASETHISTORY instance);
    #endregion
		
		public LWWDataClassesDataContext() : 
				base(global::LWWeProof.Properties.Settings.Default.LWWConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LWWDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LWWDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LWWDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LWWDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DATASETHISTORY> DATASETHISTORies
		{
			get
			{
				return this.GetTable<DATASETHISTORY>();
			}
		}
		
		public System.Data.Linq.Table<LWWWIP> LWWWIPs
		{
			get
			{
				return this.GetTable<LWWWIP>();
			}
		}
		
		public System.Data.Linq.Table<MessageDetail> MessageDetails
		{
			get
			{
				return this.GetTable<MessageDetail>();
			}
		}
		
		public System.Data.Linq.Table<UPLOADHISTORY> UPLOADHISTORies
		{
			get
			{
				return this.GetTable<UPLOADHISTORY>();
			}
		}

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.usp_GetInprocessMessageDetail")]
		public ISingleResult<usp_GetInprocessMessageDetailResult> usp_GetInprocessMessageDetail()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_GetInprocessMessageDetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_InsertDatasetHistory")]
		public int usp_InsertDatasetHistory([global::System.Data.Linq.Mapping.ParameterAttribute(Name="JID", DbType="VarChar(30)")] string jID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AID", DbType="VarChar(30)")] string aID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Stage", DbType="VarChar(30)")] string stage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jID, aID, stage);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_InsertMessageDetail")]
		public int usp_InsertMessageDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client", DbType="VarChar(30)")] string client, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="JID", DbType="VarChar(30)")] string jID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AID", DbType="VarChar(30)")] string aID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Stage", DbType="VarChar(30)")] string stage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IP", DbType="VarChar(30)")] string iP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), client, jID, aID, stage, iP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_GetDatasetHistoryRNO", IsComposable=true)]
		public System.Nullable<int> usp_GetDatasetHistoryRNO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="JID", DbType="VarChar(30)")] string jID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AID", DbType="VarChar(30)")] string aID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Stage", DbType="VarChar(30)")] string stage)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jID, aID, stage).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UpdateMessageStatus")]
        public int usp_UpdateMessageStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "MsgID", DbType = "Int")] System.Nullable<int> msgID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "WIPRno", DbType = "Int")] System.Nullable<int> wIPRno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Pages", DbType = "Int")] System.Nullable<int> pages, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Status", DbType = "VarChar(200)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), msgID, wIPRno, pages, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_GetAIDDetails")]
		public ISingleResult<usp_GetAIDDetailsResult> usp_GetAIDDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AID", DbType="VarChar(50)")] string aID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STAGE", DbType="VarChar(50)")] string sTAGE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aID, sTAGE);
			return ((ISingleResult<usp_GetAIDDetailsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATASETHISTORY")]
	public partial class DATASETHISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RNO;
		
		private string _JID;
		
		private string _AID;
		
		private string _STAGE;
		
		private System.Nullable<System.DateTime> _UPLOADDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRNOChanging(int value);
    partial void OnRNOChanged();
    partial void OnJIDChanging(string value);
    partial void OnJIDChanged();
    partial void OnAIDChanging(string value);
    partial void OnAIDChanged();
    partial void OnSTAGEChanging(string value);
    partial void OnSTAGEChanged();
    partial void OnUPLOADDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPLOADDATEChanged();
    #endregion
		
		public DATASETHISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RNO
		{
			get
			{
				return this._RNO;
			}
			set
			{
				if ((this._RNO != value))
				{
					this.OnRNOChanging(value);
					this.SendPropertyChanging();
					this._RNO = value;
					this.SendPropertyChanged("RNO");
					this.OnRNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JID", DbType="VarChar(50)")]
		public string JID
		{
			get
			{
				return this._JID;
			}
			set
			{
				if ((this._JID != value))
				{
					this.OnJIDChanging(value);
					this.SendPropertyChanging();
					this._JID = value;
					this.SendPropertyChanged("JID");
					this.OnJIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AID", DbType="VarChar(50)")]
		public string AID
		{
			get
			{
				return this._AID;
			}
			set
			{
				if ((this._AID != value))
				{
					this.OnAIDChanging(value);
					this.SendPropertyChanging();
					this._AID = value;
					this.SendPropertyChanged("AID");
					this.OnAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAGE", DbType="VarChar(50)")]
		public string STAGE
		{
			get
			{
				return this._STAGE;
			}
			set
			{
				if ((this._STAGE != value))
				{
					this.OnSTAGEChanging(value);
					this.SendPropertyChanging();
					this._STAGE = value;
					this.SendPropertyChanged("STAGE");
					this.OnSTAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOADDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPLOADDATE
		{
			get
			{
				return this._UPLOADDATE;
			}
			set
			{
				if ((this._UPLOADDATE != value))
				{
					this.OnUPLOADDATEChanging(value);
					this.SendPropertyChanging();
					this._UPLOADDATE = value;
					this.SendPropertyChanged("UPLOADDATE");
					this.OnUPLOADDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LWWWIP")]
	public partial class LWWWIP
	{
		
		private int _SNO;
		
		private string _GUID;
		
		private string _AID;
		
		private string _DOWNLOADSTATUS;
		
		private string _TASKNAME;
		
		private System.Nullable<System.DateTime> _DUEDATE;
		
		private System.Nullable<System.DateTime> _RECEIVEDDATE;
		
		private System.Nullable<System.DateTime> _SENDDATE;
		
		private System.Nullable<int> _MSS;
		
		private System.Nullable<int> _PAGES;
		
		private System.Nullable<int> _FIGCOUNT;
		
		private string _DOI;
		
		private string _CLIENT;
		
		private string _JID;
		
		private string _STAGE;
		
		private string _SERVERIP;
		
		private string _REMARKS;
		
		private string _VOL;
		
		private string _ISSUE;
		
		private string _GOXML;
		
		private string _METADATAXML;
		
		private string _GOXMLPATH;
		
		public LWWWIP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					this._SNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="VarChar(200)")]
		public string GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this._GUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AID", DbType="VarChar(50)")]
		public string AID
		{
			get
			{
				return this._AID;
			}
			set
			{
				if ((this._AID != value))
				{
					this._AID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOWNLOADSTATUS", DbType="VarChar(100)")]
		public string DOWNLOADSTATUS
		{
			get
			{
				return this._DOWNLOADSTATUS;
			}
			set
			{
				if ((this._DOWNLOADSTATUS != value))
				{
					this._DOWNLOADSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASKNAME", DbType="VarChar(200)")]
		public string TASKNAME
		{
			get
			{
				return this._TASKNAME;
			}
			set
			{
				if ((this._TASKNAME != value))
				{
					this._TASKNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DUEDATE
		{
			get
			{
				return this._DUEDATE;
			}
			set
			{
				if ((this._DUEDATE != value))
				{
					this._DUEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIVEDDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RECEIVEDDATE
		{
			get
			{
				return this._RECEIVEDDATE;
			}
			set
			{
				if ((this._RECEIVEDDATE != value))
				{
					this._RECEIVEDDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENDDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SENDDATE
		{
			get
			{
				return this._SENDDATE;
			}
			set
			{
				if ((this._SENDDATE != value))
				{
					this._SENDDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSS", DbType="Int")]
		public System.Nullable<int> MSS
		{
			get
			{
				return this._MSS;
			}
			set
			{
				if ((this._MSS != value))
				{
					this._MSS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAGES", DbType="Int")]
		public System.Nullable<int> PAGES
		{
			get
			{
				return this._PAGES;
			}
			set
			{
				if ((this._PAGES != value))
				{
					this._PAGES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIGCOUNT", DbType="Int")]
		public System.Nullable<int> FIGCOUNT
		{
			get
			{
				return this._FIGCOUNT;
			}
			set
			{
				if ((this._FIGCOUNT != value))
				{
					this._FIGCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOI", DbType="VarChar(200)")]
		public string DOI
		{
			get
			{
				return this._DOI;
			}
			set
			{
				if ((this._DOI != value))
				{
					this._DOI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT", DbType="VarChar(50)")]
		public string CLIENT
		{
			get
			{
				return this._CLIENT;
			}
			set
			{
				if ((this._CLIENT != value))
				{
					this._CLIENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JID", DbType="VarChar(50)")]
		public string JID
		{
			get
			{
				return this._JID;
			}
			set
			{
				if ((this._JID != value))
				{
					this._JID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAGE", DbType="VarChar(50)")]
		public string STAGE
		{
			get
			{
				return this._STAGE;
			}
			set
			{
				if ((this._STAGE != value))
				{
					this._STAGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVERIP", DbType="VarChar(100)")]
		public string SERVERIP
		{
			get
			{
				return this._SERVERIP;
			}
			set
			{
				if ((this._SERVERIP != value))
				{
					this._SERVERIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="VarChar(MAX)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this._REMARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOL", DbType="VarChar(50)")]
		public string VOL
		{
			get
			{
				return this._VOL;
			}
			set
			{
				if ((this._VOL != value))
				{
					this._VOL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISSUE", DbType="VarChar(50)")]
		public string ISSUE
		{
			get
			{
				return this._ISSUE;
			}
			set
			{
				if ((this._ISSUE != value))
				{
					this._ISSUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOXML", DbType="VarChar(MAX)")]
		public string GOXML
		{
			get
			{
				return this._GOXML;
			}
			set
			{
				if ((this._GOXML != value))
				{
					this._GOXML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_METADATAXML", DbType="VarChar(MAX)")]
		public string METADATAXML
		{
			get
			{
				return this._METADATAXML;
			}
			set
			{
				if ((this._METADATAXML != value))
				{
					this._METADATAXML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOXMLPATH", DbType="VarChar(500)")]
		public string GOXMLPATH
		{
			get
			{
				return this._GOXMLPATH;
			}
			set
			{
				if ((this._GOXMLPATH != value))
				{
					this._GOXMLPATH = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MessageDetail")]
	public partial class MessageDetail
	{
		
		private int _MsgID;
		
		private string _Client;
		
		private string _JID;
		
		private string _AID;
		
		private string _Stage;
		
		private string _Status;
		
		private System.DateTime _MsgDate;
		
		private string _IP;
		
		private string _JIDAID;
		
		public MessageDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MsgID
		{
			get
			{
				return this._MsgID;
			}
			set
			{
				if ((this._MsgID != value))
				{
					this._MsgID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this._Client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string JID
		{
			get
			{
				return this._JID;
			}
			set
			{
				if ((this._JID != value))
				{
					this._JID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AID
		{
			get
			{
				return this._AID;
			}
			set
			{
				if ((this._AID != value))
				{
					this._AID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Stage
		{
			get
			{
				return this._Stage;
			}
			set
			{
				if ((this._Stage != value))
				{
					this._Stage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgDate", DbType="DateTime NOT NULL")]
		public System.DateTime MsgDate
		{
			get
			{
				return this._MsgDate;
			}
			set
			{
				if ((this._MsgDate != value))
				{
					this._MsgDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(50)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this._IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JIDAID", AutoSync=AutoSync.Always, DbType="VarChar(100) NOT NULL", CanBeNull=false, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string JIDAID
		{
			get
			{
				return this._JIDAID;
			}
			set
			{
				if ((this._JIDAID != value))
				{
					this._JIDAID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UPLOADHISTORY")]
	public partial class UPLOADHISTORY
	{
		
		private int _RNO;
		
		private string _FILENAME;
		
		private System.Nullable<System.DateTime> _UPLOAD_DATE;
		
		private string _UPLOAD_STATUS;
		
		private string _REMARKS;
		
		public UPLOADHISTORY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNO", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int RNO
		{
			get
			{
				return this._RNO;
			}
			set
			{
				if ((this._RNO != value))
				{
					this._RNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILENAME", DbType="VarChar(100)")]
		public string FILENAME
		{
			get
			{
				return this._FILENAME;
			}
			set
			{
				if ((this._FILENAME != value))
				{
					this._FILENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPLOAD_DATE
		{
			get
			{
				return this._UPLOAD_DATE;
			}
			set
			{
				if ((this._UPLOAD_DATE != value))
				{
					this._UPLOAD_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_STATUS", DbType="VarChar(100)")]
		public string UPLOAD_STATUS
		{
			get
			{
				return this._UPLOAD_STATUS;
			}
			set
			{
				if ((this._UPLOAD_STATUS != value))
				{
					this._UPLOAD_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="VarChar(200)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this._REMARKS = value;
				}
			}
		}
	}
	
	public partial class usp_GetInprocessMessageDetailResult
	{
		
		private int _MsgID;
		
		private string _Client;
		
		private string _JID;
		
		private string _AID;
		
		private string _Stage;
		
		private string _Status;
		
		private System.DateTime _MsgDate;
		
		private string _IP;
		
		private string _JIDAID;
		
		public usp_GetInprocessMessageDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgID", DbType="Int NOT NULL")]
		public int MsgID
		{
			get
			{
				return this._MsgID;
			}
			set
			{
				if ((this._MsgID != value))
				{
					this._MsgID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this._Client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string JID
		{
			get
			{
				return this._JID;
			}
			set
			{
				if ((this._JID != value))
				{
					this._JID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AID
		{
			get
			{
				return this._AID;
			}
			set
			{
				if ((this._AID != value))
				{
					this._AID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Stage
		{
			get
			{
				return this._Stage;
			}
			set
			{
				if ((this._Stage != value))
				{
					this._Stage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgDate", DbType="DateTime NOT NULL")]
		public System.DateTime MsgDate
		{
			get
			{
				return this._MsgDate;
			}
			set
			{
				if ((this._MsgDate != value))
				{
					this._MsgDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(50)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this._IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JIDAID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string JIDAID
		{
			get
			{
				return this._JIDAID;
			}
			set
			{
				if ((this._JIDAID != value))
				{
					this._JIDAID = value;
				}
			}
		}
	}
	
	public partial class usp_GetAIDDetailsResult
	{
		
		private int _SNO;
		
		private string _JID;
		
		private string _AID;
		
		private string _TASKNAME;
		
		private string _STAGE;
		
		private string _GOXML;
		
		private string _METADATAXML;
		
		private string _SubmissionXML;
		
		public usp_GetAIDDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", DbType="Int NOT NULL")]
		public int SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					this._SNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JID", DbType="VarChar(50)")]
		public string JID
		{
			get
			{
				return this._JID;
			}
			set
			{
				if ((this._JID != value))
				{
					this._JID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AID", DbType="VarChar(50)")]
		public string AID
		{
			get
			{
				return this._AID;
			}
			set
			{
				if ((this._AID != value))
				{
					this._AID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASKNAME", DbType="VarChar(200)")]
		public string TASKNAME
		{
			get
			{
				return this._TASKNAME;
			}
			set
			{
				if ((this._TASKNAME != value))
				{
					this._TASKNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAGE", DbType="VarChar(50)")]
		public string STAGE
		{
			get
			{
				return this._STAGE;
			}
			set
			{
				if ((this._STAGE != value))
				{
					this._STAGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOXML", DbType="VarChar(MAX)")]
		public string GOXML
		{
			get
			{
				return this._GOXML;
			}
			set
			{
				if ((this._GOXML != value))
				{
					this._GOXML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_METADATAXML", DbType="VarChar(MAX)")]
		public string METADATAXML
		{
			get
			{
				return this._METADATAXML;
			}
			set
			{
				if ((this._METADATAXML != value))
				{
					this._METADATAXML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionXML", DbType="VarChar(MAX)")]
		public string SubmissionXML
		{
			get
			{
				return this._SubmissionXML;
			}
			set
			{
				if ((this._SubmissionXML != value))
				{
					this._SubmissionXML = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
